# Generated by Django 4.2.23 on 2025-06-18 20:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classes', '0003_classes_alter_booking_gym_class_delete_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='member',
            field=models.ForeignKey(limit_choices_to={'role': 'member'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'coach'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructed_classes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='classes.gymclass'),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('member', 'gym_class')},
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
    ]
